excludes = [
  "*.png",
  "*.jpg",
  "*.md",
  "*.lock",
  "*.zip",
  "*.css",
  "*.json",
  "*.zsh",
  "LICENSE",
  "justfile",
]

[formatter.nix]
command = "nixfmt"
includes = ["*.nix"]
options = ["-sv", "-w", "80"]

[formatter.sh]
command = "shfmt"
includes = ["*.sh"]
options = ["-l", "-w", "-ci", "-sr", "-i", "2"]

[formatter.toml]
command = "taplo"
includes = ["*.toml"]
options = [
  "fmt",
  "--option",
  "indent_string=  ",
  "--option",
  "reorder_keys=true",
]
