keys:
  - &desktop age1mqntdxsf5fxyq3mv2q2vj4zj3ep3erepje4u75mxrfj6jxuaj4cspndq8m
  - &xps7590 age1qldymwpu4l09nawcq5cnntssyprdesczsxm4gaw996mr5g8vxufs6j7558
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
    - age:
      - *desktop
      - *xps7590